### ISSUE TITLE
Plan For May

### ISSUE THREAD

**Issue by jmsalvador2395** [paser-group/iac-compiler-quality#4]
# TODO
### Goals
- [ ] 1) get 100 samples with valid syntax
	- [ ] a) count how many bugs you can generate using dumb prompts
	- [ ] b) grade relevance
- [ ] 2) try to confirm 5-10 new bugs

### Current Plan
- [x] 1) create prompt generator
	- [x] a) convert dataset into huggingface format
	- [x] b) build prompt generator class
- [x] 2) create evaluation pipeline
	- [x] a) validate syntax
	- [ ] b) mark files that require sudo access
- [x] 3) Build Testing Infrastructure
	- [x] a) Deploy ubuntu containers
	- [x] b) Automate deployment and redeployment strategies
	- [ ] c) deploy database
- [ ] 4) repeat for 3 weeks
	- [ ] a) generate list of prompts and narrow down to ~100 samples
	- [ ] b) try to implement `Ideas To Create New Bugs`
 
 

# Ideas To Create New Bugs
1. Take examples from RQ1 and ask chatgpt to generate code that would expose categorically similar vulnerabilities 
	* generate codes but without presenting examples
2. Using current bugs ask chatgpt to create new bugs that would emerge because of this bug
3. use fixed code/commit messages and prompt chatgpt to expose bugs that could potentially emerge from the fix
4. Try to expose new bugs in ansible using bugs that exist in other IaC languages
5. Check if previous bugs exist in new ansible version
6. recreate existing bugs and hopefully stumble upon new ones (**not the best idea**)
